// Copyright (c) 2022-present INESC-ID.
// Distributed under the MIT license that can be found in the LICENSE file.

// std::variant<A, B, ..> -> libcc2rs::VariantN<A, B, ..>, a Rust enum.  In the
// unsafe model the payload is stored inline, the same way rules/tuple stores a
// tuple element inline, so std::get<T> hands out a raw pointer straight into
// the enum payload and a write through it is seen by the variant.
//
// GENERATED by iso/variant/gen.py -- edit that, not this.  src.cpp explains
// why there is one rule per (arity, alternative) and why they cannot tie.

use libcc2rs::*;

// ---- arity 2 -----------------------------------------------------------

fn t1<T1: Default, T2: Default>() -> Variant2<T1, T2> {
    Default::default()
}

unsafe fn f1<T1: Default, T2: Default>() -> Variant2<T1, T2> {
    Default::default()
}

unsafe fn f2<T1: Clone, T2: Clone>(a0: Variant2<T1, T2>) -> Variant2<T1, T2> {
    a0.clone()
}

unsafe fn f3<T1: Default, T2: Default>(a0: &mut Variant2<T1, T2>) -> Variant2<T1, T2> {
    std::mem::take(&mut *a0)
}

unsafe fn f4<T1: Clone, T2: Clone>(a0: &mut Variant2<T1, T2>, a1: Variant2<T1, T2>) {
    *a0 = a1.clone()
}

unsafe fn f5<T1: Default, T2: Default>(a0: &mut Variant2<T1, T2>, a1: &mut Variant2<T1, T2>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f6<T1, T2>(a0: Variant2<T1, T2>) -> u64 {
    a0.cc2_index()
}

unsafe fn f7<T1: PartialEq, T2: PartialEq>(a0: Variant2<T1, T2>, a1: Variant2<T1, T2>) -> bool {
    (a0 == a1)
}

unsafe fn f8<T1: PartialEq, T2: PartialEq>(a0: Variant2<T1, T2>, a1: Variant2<T1, T2>) -> bool {
    (a0 != a1)
}

unsafe fn f9<T1, T2>(a0: T1) -> Variant2<T1, T2> {
    Variant2::V1(a0)
}

unsafe fn f10<T1, T2>(a0: T1) -> Variant2<T1, T2> {
    Variant2::V1(a0)
}

unsafe fn f11<T1, T2>(a0: T1) -> Variant2<T1, T2> {
    Variant2::V1(a0)
}

unsafe fn f12<T1, T2>(a0: &mut Variant2<T1, T2>, a1: T1) {
    *a0 = Variant2::V1(a1)
}

unsafe fn f13<T1, T2>(a0: &mut Variant2<T1, T2>, a1: T1) {
    *a0 = Variant2::V1(a1)
}

unsafe fn f14<T1, T2>(a0: &mut Variant2<T1, T2>, a1: T1) {
    *a0 = Variant2::V1(a1)
}

unsafe fn f15<T1, T2>(a0: Variant2<T1, T2>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f16<T1, T2>(a0: *mut Variant2<T1, T2>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f17<T1, T2>(a0: *const Variant2<T1, T2>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f18<T1, T2>(a0: T2) -> Variant2<T1, T2> {
    Variant2::V2(a0)
}

unsafe fn f19<T1, T2>(a0: T2) -> Variant2<T1, T2> {
    Variant2::V2(a0)
}

unsafe fn f20<T1, T2>(a0: T2) -> Variant2<T1, T2> {
    Variant2::V2(a0)
}

unsafe fn f21<T1, T2>(a0: &mut Variant2<T1, T2>, a1: T2) {
    *a0 = Variant2::V2(a1)
}

unsafe fn f22<T1, T2>(a0: &mut Variant2<T1, T2>, a1: T2) {
    *a0 = Variant2::V2(a1)
}

unsafe fn f23<T1, T2>(a0: &mut Variant2<T1, T2>, a1: T2) {
    *a0 = Variant2::V2(a1)
}

unsafe fn f24<T1, T2>(a0: Variant2<T1, T2>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f25<T1, T2>(a0: *mut Variant2<T1, T2>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f26<T1, T2>(a0: *const Variant2<T1, T2>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

// ---- arity 3 -----------------------------------------------------------

fn t2<T1: Default, T2: Default, T3: Default>() -> Variant3<T1, T2, T3> {
    Default::default()
}

unsafe fn f27<T1: Default, T2: Default, T3: Default>() -> Variant3<T1, T2, T3> {
    Default::default()
}

unsafe fn f28<T1: Clone, T2: Clone, T3: Clone>(a0: Variant3<T1, T2, T3>) -> Variant3<T1, T2, T3> {
    a0.clone()
}

unsafe fn f29<T1: Default, T2: Default, T3: Default>(a0: &mut Variant3<T1, T2, T3>) -> Variant3<T1, T2, T3> {
    std::mem::take(&mut *a0)
}

unsafe fn f30<T1: Clone, T2: Clone, T3: Clone>(a0: &mut Variant3<T1, T2, T3>, a1: Variant3<T1, T2, T3>) {
    *a0 = a1.clone()
}

unsafe fn f31<T1: Default, T2: Default, T3: Default>(a0: &mut Variant3<T1, T2, T3>, a1: &mut Variant3<T1, T2, T3>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f32<T1, T2, T3>(a0: Variant3<T1, T2, T3>) -> u64 {
    a0.cc2_index()
}

unsafe fn f33<T1: PartialEq, T2: PartialEq, T3: PartialEq>(a0: Variant3<T1, T2, T3>, a1: Variant3<T1, T2, T3>) -> bool {
    (a0 == a1)
}

unsafe fn f34<T1: PartialEq, T2: PartialEq, T3: PartialEq>(a0: Variant3<T1, T2, T3>, a1: Variant3<T1, T2, T3>) -> bool {
    (a0 != a1)
}

unsafe fn f35<T1, T2, T3>(a0: T1) -> Variant3<T1, T2, T3> {
    Variant3::V1(a0)
}

unsafe fn f36<T1, T2, T3>(a0: T1) -> Variant3<T1, T2, T3> {
    Variant3::V1(a0)
}

unsafe fn f37<T1, T2, T3>(a0: T1) -> Variant3<T1, T2, T3> {
    Variant3::V1(a0)
}

unsafe fn f38<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T1) {
    *a0 = Variant3::V1(a1)
}

unsafe fn f39<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T1) {
    *a0 = Variant3::V1(a1)
}

unsafe fn f40<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T1) {
    *a0 = Variant3::V1(a1)
}

unsafe fn f41<T1, T2, T3>(a0: Variant3<T1, T2, T3>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f42<T1, T2, T3>(a0: *mut Variant3<T1, T2, T3>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f43<T1, T2, T3>(a0: *const Variant3<T1, T2, T3>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f44<T1, T2, T3>(a0: T2) -> Variant3<T1, T2, T3> {
    Variant3::V2(a0)
}

unsafe fn f45<T1, T2, T3>(a0: T2) -> Variant3<T1, T2, T3> {
    Variant3::V2(a0)
}

unsafe fn f46<T1, T2, T3>(a0: T2) -> Variant3<T1, T2, T3> {
    Variant3::V2(a0)
}

unsafe fn f47<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T2) {
    *a0 = Variant3::V2(a1)
}

unsafe fn f48<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T2) {
    *a0 = Variant3::V2(a1)
}

unsafe fn f49<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T2) {
    *a0 = Variant3::V2(a1)
}

unsafe fn f50<T1, T2, T3>(a0: Variant3<T1, T2, T3>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f51<T1, T2, T3>(a0: *mut Variant3<T1, T2, T3>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f52<T1, T2, T3>(a0: *const Variant3<T1, T2, T3>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

unsafe fn f53<T1, T2, T3>(a0: T3) -> Variant3<T1, T2, T3> {
    Variant3::V3(a0)
}

unsafe fn f54<T1, T2, T3>(a0: T3) -> Variant3<T1, T2, T3> {
    Variant3::V3(a0)
}

unsafe fn f55<T1, T2, T3>(a0: T3) -> Variant3<T1, T2, T3> {
    Variant3::V3(a0)
}

unsafe fn f56<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T3) {
    *a0 = Variant3::V3(a1)
}

unsafe fn f57<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T3) {
    *a0 = Variant3::V3(a1)
}

unsafe fn f58<T1, T2, T3>(a0: &mut Variant3<T1, T2, T3>, a1: T3) {
    *a0 = Variant3::V3(a1)
}

unsafe fn f59<T1, T2, T3>(a0: Variant3<T1, T2, T3>) -> bool {
    a0.cc2_holds_3()
}

unsafe fn f60<T1, T2, T3>(a0: *mut Variant3<T1, T2, T3>) -> *mut T3 {
    ((*a0).cc2_3_mut() as *mut T3)
}

unsafe fn f61<T1, T2, T3>(a0: *const Variant3<T1, T2, T3>) -> *const T3 {
    ((*a0).cc2_3() as *const T3)
}

// ---- arity 4 -----------------------------------------------------------

fn t3<T1: Default, T2: Default, T3: Default, T4: Default>() -> Variant4<T1, T2, T3, T4> {
    Default::default()
}

unsafe fn f62<T1: Default, T2: Default, T3: Default, T4: Default>() -> Variant4<T1, T2, T3, T4> {
    Default::default()
}

unsafe fn f63<T1: Clone, T2: Clone, T3: Clone, T4: Clone>(a0: Variant4<T1, T2, T3, T4>) -> Variant4<T1, T2, T3, T4> {
    a0.clone()
}

unsafe fn f64<T1: Default, T2: Default, T3: Default, T4: Default>(a0: &mut Variant4<T1, T2, T3, T4>) -> Variant4<T1, T2, T3, T4> {
    std::mem::take(&mut *a0)
}

unsafe fn f65<T1: Clone, T2: Clone, T3: Clone, T4: Clone>(a0: &mut Variant4<T1, T2, T3, T4>, a1: Variant4<T1, T2, T3, T4>) {
    *a0 = a1.clone()
}

unsafe fn f66<T1: Default, T2: Default, T3: Default, T4: Default>(a0: &mut Variant4<T1, T2, T3, T4>, a1: &mut Variant4<T1, T2, T3, T4>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f67<T1, T2, T3, T4>(a0: Variant4<T1, T2, T3, T4>) -> u64 {
    a0.cc2_index()
}

unsafe fn f68<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq>(a0: Variant4<T1, T2, T3, T4>, a1: Variant4<T1, T2, T3, T4>) -> bool {
    (a0 == a1)
}

unsafe fn f69<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq>(a0: Variant4<T1, T2, T3, T4>, a1: Variant4<T1, T2, T3, T4>) -> bool {
    (a0 != a1)
}

unsafe fn f70<T1, T2, T3, T4>(a0: T1) -> Variant4<T1, T2, T3, T4> {
    Variant4::V1(a0)
}

unsafe fn f71<T1, T2, T3, T4>(a0: T1) -> Variant4<T1, T2, T3, T4> {
    Variant4::V1(a0)
}

unsafe fn f72<T1, T2, T3, T4>(a0: T1) -> Variant4<T1, T2, T3, T4> {
    Variant4::V1(a0)
}

unsafe fn f73<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T1) {
    *a0 = Variant4::V1(a1)
}

unsafe fn f74<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T1) {
    *a0 = Variant4::V1(a1)
}

unsafe fn f75<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T1) {
    *a0 = Variant4::V1(a1)
}

unsafe fn f76<T1, T2, T3, T4>(a0: Variant4<T1, T2, T3, T4>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f77<T1, T2, T3, T4>(a0: *mut Variant4<T1, T2, T3, T4>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f78<T1, T2, T3, T4>(a0: *const Variant4<T1, T2, T3, T4>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f79<T1, T2, T3, T4>(a0: T2) -> Variant4<T1, T2, T3, T4> {
    Variant4::V2(a0)
}

unsafe fn f80<T1, T2, T3, T4>(a0: T2) -> Variant4<T1, T2, T3, T4> {
    Variant4::V2(a0)
}

unsafe fn f81<T1, T2, T3, T4>(a0: T2) -> Variant4<T1, T2, T3, T4> {
    Variant4::V2(a0)
}

unsafe fn f82<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T2) {
    *a0 = Variant4::V2(a1)
}

unsafe fn f83<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T2) {
    *a0 = Variant4::V2(a1)
}

unsafe fn f84<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T2) {
    *a0 = Variant4::V2(a1)
}

unsafe fn f85<T1, T2, T3, T4>(a0: Variant4<T1, T2, T3, T4>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f86<T1, T2, T3, T4>(a0: *mut Variant4<T1, T2, T3, T4>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f87<T1, T2, T3, T4>(a0: *const Variant4<T1, T2, T3, T4>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

unsafe fn f88<T1, T2, T3, T4>(a0: T3) -> Variant4<T1, T2, T3, T4> {
    Variant4::V3(a0)
}

unsafe fn f89<T1, T2, T3, T4>(a0: T3) -> Variant4<T1, T2, T3, T4> {
    Variant4::V3(a0)
}

unsafe fn f90<T1, T2, T3, T4>(a0: T3) -> Variant4<T1, T2, T3, T4> {
    Variant4::V3(a0)
}

unsafe fn f91<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T3) {
    *a0 = Variant4::V3(a1)
}

unsafe fn f92<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T3) {
    *a0 = Variant4::V3(a1)
}

unsafe fn f93<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T3) {
    *a0 = Variant4::V3(a1)
}

unsafe fn f94<T1, T2, T3, T4>(a0: Variant4<T1, T2, T3, T4>) -> bool {
    a0.cc2_holds_3()
}

unsafe fn f95<T1, T2, T3, T4>(a0: *mut Variant4<T1, T2, T3, T4>) -> *mut T3 {
    ((*a0).cc2_3_mut() as *mut T3)
}

unsafe fn f96<T1, T2, T3, T4>(a0: *const Variant4<T1, T2, T3, T4>) -> *const T3 {
    ((*a0).cc2_3() as *const T3)
}

unsafe fn f97<T1, T2, T3, T4>(a0: T4) -> Variant4<T1, T2, T3, T4> {
    Variant4::V4(a0)
}

unsafe fn f98<T1, T2, T3, T4>(a0: T4) -> Variant4<T1, T2, T3, T4> {
    Variant4::V4(a0)
}

unsafe fn f99<T1, T2, T3, T4>(a0: T4) -> Variant4<T1, T2, T3, T4> {
    Variant4::V4(a0)
}

unsafe fn f100<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T4) {
    *a0 = Variant4::V4(a1)
}

unsafe fn f101<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T4) {
    *a0 = Variant4::V4(a1)
}

unsafe fn f102<T1, T2, T3, T4>(a0: &mut Variant4<T1, T2, T3, T4>, a1: T4) {
    *a0 = Variant4::V4(a1)
}

unsafe fn f103<T1, T2, T3, T4>(a0: Variant4<T1, T2, T3, T4>) -> bool {
    a0.cc2_holds_4()
}

unsafe fn f104<T1, T2, T3, T4>(a0: *mut Variant4<T1, T2, T3, T4>) -> *mut T4 {
    ((*a0).cc2_4_mut() as *mut T4)
}

unsafe fn f105<T1, T2, T3, T4>(a0: *const Variant4<T1, T2, T3, T4>) -> *const T4 {
    ((*a0).cc2_4() as *const T4)
}

// ---- arity 5 -----------------------------------------------------------

fn t4<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>() -> Variant5<T1, T2, T3, T4, T5> {
    Default::default()
}

unsafe fn f106<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>() -> Variant5<T1, T2, T3, T4, T5> {
    Default::default()
}

unsafe fn f107<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone>(a0: Variant5<T1, T2, T3, T4, T5>) -> Variant5<T1, T2, T3, T4, T5> {
    a0.clone()
}

unsafe fn f108<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>(a0: &mut Variant5<T1, T2, T3, T4, T5>) -> Variant5<T1, T2, T3, T4, T5> {
    std::mem::take(&mut *a0)
}

unsafe fn f109<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: Variant5<T1, T2, T3, T4, T5>) {
    *a0 = a1.clone()
}

unsafe fn f110<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: &mut Variant5<T1, T2, T3, T4, T5>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f111<T1, T2, T3, T4, T5>(a0: Variant5<T1, T2, T3, T4, T5>) -> u64 {
    a0.cc2_index()
}

unsafe fn f112<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq>(a0: Variant5<T1, T2, T3, T4, T5>, a1: Variant5<T1, T2, T3, T4, T5>) -> bool {
    (a0 == a1)
}

unsafe fn f113<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq>(a0: Variant5<T1, T2, T3, T4, T5>, a1: Variant5<T1, T2, T3, T4, T5>) -> bool {
    (a0 != a1)
}

unsafe fn f114<T1, T2, T3, T4, T5>(a0: T1) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V1(a0)
}

unsafe fn f115<T1, T2, T3, T4, T5>(a0: T1) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V1(a0)
}

unsafe fn f116<T1, T2, T3, T4, T5>(a0: T1) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V1(a0)
}

unsafe fn f117<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T1) {
    *a0 = Variant5::V1(a1)
}

unsafe fn f118<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T1) {
    *a0 = Variant5::V1(a1)
}

unsafe fn f119<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T1) {
    *a0 = Variant5::V1(a1)
}

unsafe fn f120<T1, T2, T3, T4, T5>(a0: Variant5<T1, T2, T3, T4, T5>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f121<T1, T2, T3, T4, T5>(a0: *mut Variant5<T1, T2, T3, T4, T5>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f122<T1, T2, T3, T4, T5>(a0: *const Variant5<T1, T2, T3, T4, T5>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f123<T1, T2, T3, T4, T5>(a0: T2) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V2(a0)
}

unsafe fn f124<T1, T2, T3, T4, T5>(a0: T2) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V2(a0)
}

unsafe fn f125<T1, T2, T3, T4, T5>(a0: T2) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V2(a0)
}

unsafe fn f126<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T2) {
    *a0 = Variant5::V2(a1)
}

unsafe fn f127<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T2) {
    *a0 = Variant5::V2(a1)
}

unsafe fn f128<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T2) {
    *a0 = Variant5::V2(a1)
}

unsafe fn f129<T1, T2, T3, T4, T5>(a0: Variant5<T1, T2, T3, T4, T5>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f130<T1, T2, T3, T4, T5>(a0: *mut Variant5<T1, T2, T3, T4, T5>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f131<T1, T2, T3, T4, T5>(a0: *const Variant5<T1, T2, T3, T4, T5>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

unsafe fn f132<T1, T2, T3, T4, T5>(a0: T3) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V3(a0)
}

unsafe fn f133<T1, T2, T3, T4, T5>(a0: T3) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V3(a0)
}

unsafe fn f134<T1, T2, T3, T4, T5>(a0: T3) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V3(a0)
}

unsafe fn f135<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T3) {
    *a0 = Variant5::V3(a1)
}

unsafe fn f136<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T3) {
    *a0 = Variant5::V3(a1)
}

unsafe fn f137<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T3) {
    *a0 = Variant5::V3(a1)
}

unsafe fn f138<T1, T2, T3, T4, T5>(a0: Variant5<T1, T2, T3, T4, T5>) -> bool {
    a0.cc2_holds_3()
}

unsafe fn f139<T1, T2, T3, T4, T5>(a0: *mut Variant5<T1, T2, T3, T4, T5>) -> *mut T3 {
    ((*a0).cc2_3_mut() as *mut T3)
}

unsafe fn f140<T1, T2, T3, T4, T5>(a0: *const Variant5<T1, T2, T3, T4, T5>) -> *const T3 {
    ((*a0).cc2_3() as *const T3)
}

unsafe fn f141<T1, T2, T3, T4, T5>(a0: T4) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V4(a0)
}

unsafe fn f142<T1, T2, T3, T4, T5>(a0: T4) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V4(a0)
}

unsafe fn f143<T1, T2, T3, T4, T5>(a0: T4) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V4(a0)
}

unsafe fn f144<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T4) {
    *a0 = Variant5::V4(a1)
}

unsafe fn f145<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T4) {
    *a0 = Variant5::V4(a1)
}

unsafe fn f146<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T4) {
    *a0 = Variant5::V4(a1)
}

unsafe fn f147<T1, T2, T3, T4, T5>(a0: Variant5<T1, T2, T3, T4, T5>) -> bool {
    a0.cc2_holds_4()
}

unsafe fn f148<T1, T2, T3, T4, T5>(a0: *mut Variant5<T1, T2, T3, T4, T5>) -> *mut T4 {
    ((*a0).cc2_4_mut() as *mut T4)
}

unsafe fn f149<T1, T2, T3, T4, T5>(a0: *const Variant5<T1, T2, T3, T4, T5>) -> *const T4 {
    ((*a0).cc2_4() as *const T4)
}

unsafe fn f150<T1, T2, T3, T4, T5>(a0: T5) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V5(a0)
}

unsafe fn f151<T1, T2, T3, T4, T5>(a0: T5) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V5(a0)
}

unsafe fn f152<T1, T2, T3, T4, T5>(a0: T5) -> Variant5<T1, T2, T3, T4, T5> {
    Variant5::V5(a0)
}

unsafe fn f153<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T5) {
    *a0 = Variant5::V5(a1)
}

unsafe fn f154<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T5) {
    *a0 = Variant5::V5(a1)
}

unsafe fn f155<T1, T2, T3, T4, T5>(a0: &mut Variant5<T1, T2, T3, T4, T5>, a1: T5) {
    *a0 = Variant5::V5(a1)
}

unsafe fn f156<T1, T2, T3, T4, T5>(a0: Variant5<T1, T2, T3, T4, T5>) -> bool {
    a0.cc2_holds_5()
}

unsafe fn f157<T1, T2, T3, T4, T5>(a0: *mut Variant5<T1, T2, T3, T4, T5>) -> *mut T5 {
    ((*a0).cc2_5_mut() as *mut T5)
}

unsafe fn f158<T1, T2, T3, T4, T5>(a0: *const Variant5<T1, T2, T3, T4, T5>) -> *const T5 {
    ((*a0).cc2_5() as *const T5)
}

// ---- arity 6 -----------------------------------------------------------

fn t5<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>() -> Variant6<T1, T2, T3, T4, T5, T6> {
    Default::default()
}

unsafe fn f159<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>() -> Variant6<T1, T2, T3, T4, T5, T6> {
    Default::default()
}

unsafe fn f160<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone, T6: Clone>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> Variant6<T1, T2, T3, T4, T5, T6> {
    a0.clone()
}

unsafe fn f161<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>) -> Variant6<T1, T2, T3, T4, T5, T6> {
    std::mem::take(&mut *a0)
}

unsafe fn f162<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone, T6: Clone>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: Variant6<T1, T2, T3, T4, T5, T6>) {
    *a0 = a1.clone()
}

unsafe fn f163<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: &mut Variant6<T1, T2, T3, T4, T5, T6>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f164<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> u64 {
    a0.cc2_index()
}

unsafe fn f165<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq>(a0: Variant6<T1, T2, T3, T4, T5, T6>, a1: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    (a0 == a1)
}

unsafe fn f166<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq>(a0: Variant6<T1, T2, T3, T4, T5, T6>, a1: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    (a0 != a1)
}

unsafe fn f167<T1, T2, T3, T4, T5, T6>(a0: T1) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V1(a0)
}

unsafe fn f168<T1, T2, T3, T4, T5, T6>(a0: T1) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V1(a0)
}

unsafe fn f169<T1, T2, T3, T4, T5, T6>(a0: T1) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V1(a0)
}

unsafe fn f170<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T1) {
    *a0 = Variant6::V1(a1)
}

unsafe fn f171<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T1) {
    *a0 = Variant6::V1(a1)
}

unsafe fn f172<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T1) {
    *a0 = Variant6::V1(a1)
}

unsafe fn f173<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f174<T1, T2, T3, T4, T5, T6>(a0: *mut Variant6<T1, T2, T3, T4, T5, T6>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f175<T1, T2, T3, T4, T5, T6>(a0: *const Variant6<T1, T2, T3, T4, T5, T6>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f176<T1, T2, T3, T4, T5, T6>(a0: T2) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V2(a0)
}

unsafe fn f177<T1, T2, T3, T4, T5, T6>(a0: T2) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V2(a0)
}

unsafe fn f178<T1, T2, T3, T4, T5, T6>(a0: T2) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V2(a0)
}

unsafe fn f179<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T2) {
    *a0 = Variant6::V2(a1)
}

unsafe fn f180<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T2) {
    *a0 = Variant6::V2(a1)
}

unsafe fn f181<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T2) {
    *a0 = Variant6::V2(a1)
}

unsafe fn f182<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f183<T1, T2, T3, T4, T5, T6>(a0: *mut Variant6<T1, T2, T3, T4, T5, T6>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f184<T1, T2, T3, T4, T5, T6>(a0: *const Variant6<T1, T2, T3, T4, T5, T6>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

unsafe fn f185<T1, T2, T3, T4, T5, T6>(a0: T3) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V3(a0)
}

unsafe fn f186<T1, T2, T3, T4, T5, T6>(a0: T3) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V3(a0)
}

unsafe fn f187<T1, T2, T3, T4, T5, T6>(a0: T3) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V3(a0)
}

unsafe fn f188<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T3) {
    *a0 = Variant6::V3(a1)
}

unsafe fn f189<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T3) {
    *a0 = Variant6::V3(a1)
}

unsafe fn f190<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T3) {
    *a0 = Variant6::V3(a1)
}

unsafe fn f191<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    a0.cc2_holds_3()
}

unsafe fn f192<T1, T2, T3, T4, T5, T6>(a0: *mut Variant6<T1, T2, T3, T4, T5, T6>) -> *mut T3 {
    ((*a0).cc2_3_mut() as *mut T3)
}

unsafe fn f193<T1, T2, T3, T4, T5, T6>(a0: *const Variant6<T1, T2, T3, T4, T5, T6>) -> *const T3 {
    ((*a0).cc2_3() as *const T3)
}

unsafe fn f194<T1, T2, T3, T4, T5, T6>(a0: T4) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V4(a0)
}

unsafe fn f195<T1, T2, T3, T4, T5, T6>(a0: T4) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V4(a0)
}

unsafe fn f196<T1, T2, T3, T4, T5, T6>(a0: T4) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V4(a0)
}

unsafe fn f197<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T4) {
    *a0 = Variant6::V4(a1)
}

unsafe fn f198<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T4) {
    *a0 = Variant6::V4(a1)
}

unsafe fn f199<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T4) {
    *a0 = Variant6::V4(a1)
}

unsafe fn f200<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    a0.cc2_holds_4()
}

unsafe fn f201<T1, T2, T3, T4, T5, T6>(a0: *mut Variant6<T1, T2, T3, T4, T5, T6>) -> *mut T4 {
    ((*a0).cc2_4_mut() as *mut T4)
}

unsafe fn f202<T1, T2, T3, T4, T5, T6>(a0: *const Variant6<T1, T2, T3, T4, T5, T6>) -> *const T4 {
    ((*a0).cc2_4() as *const T4)
}

unsafe fn f203<T1, T2, T3, T4, T5, T6>(a0: T5) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V5(a0)
}

unsafe fn f204<T1, T2, T3, T4, T5, T6>(a0: T5) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V5(a0)
}

unsafe fn f205<T1, T2, T3, T4, T5, T6>(a0: T5) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V5(a0)
}

unsafe fn f206<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T5) {
    *a0 = Variant6::V5(a1)
}

unsafe fn f207<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T5) {
    *a0 = Variant6::V5(a1)
}

unsafe fn f208<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T5) {
    *a0 = Variant6::V5(a1)
}

unsafe fn f209<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    a0.cc2_holds_5()
}

unsafe fn f210<T1, T2, T3, T4, T5, T6>(a0: *mut Variant6<T1, T2, T3, T4, T5, T6>) -> *mut T5 {
    ((*a0).cc2_5_mut() as *mut T5)
}

unsafe fn f211<T1, T2, T3, T4, T5, T6>(a0: *const Variant6<T1, T2, T3, T4, T5, T6>) -> *const T5 {
    ((*a0).cc2_5() as *const T5)
}

unsafe fn f212<T1, T2, T3, T4, T5, T6>(a0: T6) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V6(a0)
}

unsafe fn f213<T1, T2, T3, T4, T5, T6>(a0: T6) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V6(a0)
}

unsafe fn f214<T1, T2, T3, T4, T5, T6>(a0: T6) -> Variant6<T1, T2, T3, T4, T5, T6> {
    Variant6::V6(a0)
}

unsafe fn f215<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T6) {
    *a0 = Variant6::V6(a1)
}

unsafe fn f216<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T6) {
    *a0 = Variant6::V6(a1)
}

unsafe fn f217<T1, T2, T3, T4, T5, T6>(a0: &mut Variant6<T1, T2, T3, T4, T5, T6>, a1: T6) {
    *a0 = Variant6::V6(a1)
}

unsafe fn f218<T1, T2, T3, T4, T5, T6>(a0: Variant6<T1, T2, T3, T4, T5, T6>) -> bool {
    a0.cc2_holds_6()
}

unsafe fn f219<T1, T2, T3, T4, T5, T6>(a0: *mut Variant6<T1, T2, T3, T4, T5, T6>) -> *mut T6 {
    ((*a0).cc2_6_mut() as *mut T6)
}

unsafe fn f220<T1, T2, T3, T4, T5, T6>(a0: *const Variant6<T1, T2, T3, T4, T5, T6>) -> *const T6 {
    ((*a0).cc2_6() as *const T6)
}

// ---- arity 7 -----------------------------------------------------------

fn t6<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>() -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Default::default()
}

unsafe fn f221<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>() -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Default::default()
}

unsafe fn f222<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone, T6: Clone, T7: Clone>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    a0.clone()
}

unsafe fn f223<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    std::mem::take(&mut *a0)
}

unsafe fn f224<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone, T6: Clone, T7: Clone>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: Variant7<T1, T2, T3, T4, T5, T6, T7>) {
    *a0 = a1.clone()
}

unsafe fn f225<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f226<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> u64 {
    a0.cc2_index()
}

unsafe fn f227<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    (a0 == a1)
}

unsafe fn f228<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    (a0 != a1)
}

unsafe fn f229<T1, T2, T3, T4, T5, T6, T7>(a0: T1) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V1(a0)
}

unsafe fn f230<T1, T2, T3, T4, T5, T6, T7>(a0: T1) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V1(a0)
}

unsafe fn f231<T1, T2, T3, T4, T5, T6, T7>(a0: T1) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V1(a0)
}

unsafe fn f232<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T1) {
    *a0 = Variant7::V1(a1)
}

unsafe fn f233<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T1) {
    *a0 = Variant7::V1(a1)
}

unsafe fn f234<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T1) {
    *a0 = Variant7::V1(a1)
}

unsafe fn f235<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f236<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f237<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f238<T1, T2, T3, T4, T5, T6, T7>(a0: T2) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V2(a0)
}

unsafe fn f239<T1, T2, T3, T4, T5, T6, T7>(a0: T2) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V2(a0)
}

unsafe fn f240<T1, T2, T3, T4, T5, T6, T7>(a0: T2) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V2(a0)
}

unsafe fn f241<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T2) {
    *a0 = Variant7::V2(a1)
}

unsafe fn f242<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T2) {
    *a0 = Variant7::V2(a1)
}

unsafe fn f243<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T2) {
    *a0 = Variant7::V2(a1)
}

unsafe fn f244<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f245<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f246<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

unsafe fn f247<T1, T2, T3, T4, T5, T6, T7>(a0: T3) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V3(a0)
}

unsafe fn f248<T1, T2, T3, T4, T5, T6, T7>(a0: T3) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V3(a0)
}

unsafe fn f249<T1, T2, T3, T4, T5, T6, T7>(a0: T3) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V3(a0)
}

unsafe fn f250<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T3) {
    *a0 = Variant7::V3(a1)
}

unsafe fn f251<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T3) {
    *a0 = Variant7::V3(a1)
}

unsafe fn f252<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T3) {
    *a0 = Variant7::V3(a1)
}

unsafe fn f253<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_3()
}

unsafe fn f254<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T3 {
    ((*a0).cc2_3_mut() as *mut T3)
}

unsafe fn f255<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T3 {
    ((*a0).cc2_3() as *const T3)
}

unsafe fn f256<T1, T2, T3, T4, T5, T6, T7>(a0: T4) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V4(a0)
}

unsafe fn f257<T1, T2, T3, T4, T5, T6, T7>(a0: T4) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V4(a0)
}

unsafe fn f258<T1, T2, T3, T4, T5, T6, T7>(a0: T4) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V4(a0)
}

unsafe fn f259<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T4) {
    *a0 = Variant7::V4(a1)
}

unsafe fn f260<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T4) {
    *a0 = Variant7::V4(a1)
}

unsafe fn f261<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T4) {
    *a0 = Variant7::V4(a1)
}

unsafe fn f262<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_4()
}

unsafe fn f263<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T4 {
    ((*a0).cc2_4_mut() as *mut T4)
}

unsafe fn f264<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T4 {
    ((*a0).cc2_4() as *const T4)
}

unsafe fn f265<T1, T2, T3, T4, T5, T6, T7>(a0: T5) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V5(a0)
}

unsafe fn f266<T1, T2, T3, T4, T5, T6, T7>(a0: T5) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V5(a0)
}

unsafe fn f267<T1, T2, T3, T4, T5, T6, T7>(a0: T5) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V5(a0)
}

unsafe fn f268<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T5) {
    *a0 = Variant7::V5(a1)
}

unsafe fn f269<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T5) {
    *a0 = Variant7::V5(a1)
}

unsafe fn f270<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T5) {
    *a0 = Variant7::V5(a1)
}

unsafe fn f271<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_5()
}

unsafe fn f272<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T5 {
    ((*a0).cc2_5_mut() as *mut T5)
}

unsafe fn f273<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T5 {
    ((*a0).cc2_5() as *const T5)
}

unsafe fn f274<T1, T2, T3, T4, T5, T6, T7>(a0: T6) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V6(a0)
}

unsafe fn f275<T1, T2, T3, T4, T5, T6, T7>(a0: T6) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V6(a0)
}

unsafe fn f276<T1, T2, T3, T4, T5, T6, T7>(a0: T6) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V6(a0)
}

unsafe fn f277<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T6) {
    *a0 = Variant7::V6(a1)
}

unsafe fn f278<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T6) {
    *a0 = Variant7::V6(a1)
}

unsafe fn f279<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T6) {
    *a0 = Variant7::V6(a1)
}

unsafe fn f280<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_6()
}

unsafe fn f281<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T6 {
    ((*a0).cc2_6_mut() as *mut T6)
}

unsafe fn f282<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T6 {
    ((*a0).cc2_6() as *const T6)
}

unsafe fn f283<T1, T2, T3, T4, T5, T6, T7>(a0: T7) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V7(a0)
}

unsafe fn f284<T1, T2, T3, T4, T5, T6, T7>(a0: T7) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V7(a0)
}

unsafe fn f285<T1, T2, T3, T4, T5, T6, T7>(a0: T7) -> Variant7<T1, T2, T3, T4, T5, T6, T7> {
    Variant7::V7(a0)
}

unsafe fn f286<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T7) {
    *a0 = Variant7::V7(a1)
}

unsafe fn f287<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T7) {
    *a0 = Variant7::V7(a1)
}

unsafe fn f288<T1, T2, T3, T4, T5, T6, T7>(a0: &mut Variant7<T1, T2, T3, T4, T5, T6, T7>, a1: T7) {
    *a0 = Variant7::V7(a1)
}

unsafe fn f289<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<T1, T2, T3, T4, T5, T6, T7>) -> bool {
    a0.cc2_holds_7()
}

unsafe fn f290<T1, T2, T3, T4, T5, T6, T7>(a0: *mut Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *mut T7 {
    ((*a0).cc2_7_mut() as *mut T7)
}

unsafe fn f291<T1, T2, T3, T4, T5, T6, T7>(a0: *const Variant7<T1, T2, T3, T4, T5, T6, T7>) -> *const T7 {
    ((*a0).cc2_7() as *const T7)
}

// ---- arity 8 -----------------------------------------------------------

fn t7<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>() -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Default::default()
}

unsafe fn f292<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>() -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Default::default()
}

unsafe fn f293<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone, T6: Clone, T7: Clone, T8: Clone>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    a0.clone()
}

unsafe fn f294<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    std::mem::take(&mut *a0)
}

unsafe fn f295<T1: Clone, T2: Clone, T3: Clone, T4: Clone, T5: Clone, T6: Clone, T7: Clone, T8: Clone>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) {
    *a0 = a1.clone()
}

unsafe fn f296<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) {
    *a0 = std::mem::take(&mut *a1)
}

unsafe fn f297<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> u64 {
    a0.cc2_index()
}

unsafe fn f298<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq, T8: PartialEq>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    (a0 == a1)
}

unsafe fn f299<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq, T8: PartialEq>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    (a0 != a1)
}

unsafe fn f300<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T1) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V1(a0)
}

unsafe fn f301<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T1) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V1(a0)
}

unsafe fn f302<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T1) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V1(a0)
}

unsafe fn f303<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T1) {
    *a0 = Variant8::V1(a1)
}

unsafe fn f304<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T1) {
    *a0 = Variant8::V1(a1)
}

unsafe fn f305<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T1) {
    *a0 = Variant8::V1(a1)
}

unsafe fn f306<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_1()
}

unsafe fn f307<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T1 {
    ((*a0).cc2_1_mut() as *mut T1)
}

unsafe fn f308<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T1 {
    ((*a0).cc2_1() as *const T1)
}

unsafe fn f309<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T2) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V2(a0)
}

unsafe fn f310<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T2) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V2(a0)
}

unsafe fn f311<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T2) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V2(a0)
}

unsafe fn f312<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T2) {
    *a0 = Variant8::V2(a1)
}

unsafe fn f313<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T2) {
    *a0 = Variant8::V2(a1)
}

unsafe fn f314<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T2) {
    *a0 = Variant8::V2(a1)
}

unsafe fn f315<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_2()
}

unsafe fn f316<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T2 {
    ((*a0).cc2_2_mut() as *mut T2)
}

unsafe fn f317<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T2 {
    ((*a0).cc2_2() as *const T2)
}

unsafe fn f318<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T3) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V3(a0)
}

unsafe fn f319<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T3) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V3(a0)
}

unsafe fn f320<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T3) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V3(a0)
}

unsafe fn f321<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T3) {
    *a0 = Variant8::V3(a1)
}

unsafe fn f322<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T3) {
    *a0 = Variant8::V3(a1)
}

unsafe fn f323<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T3) {
    *a0 = Variant8::V3(a1)
}

unsafe fn f324<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_3()
}

unsafe fn f325<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T3 {
    ((*a0).cc2_3_mut() as *mut T3)
}

unsafe fn f326<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T3 {
    ((*a0).cc2_3() as *const T3)
}

unsafe fn f327<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T4) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V4(a0)
}

unsafe fn f328<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T4) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V4(a0)
}

unsafe fn f329<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T4) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V4(a0)
}

unsafe fn f330<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T4) {
    *a0 = Variant8::V4(a1)
}

unsafe fn f331<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T4) {
    *a0 = Variant8::V4(a1)
}

unsafe fn f332<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T4) {
    *a0 = Variant8::V4(a1)
}

unsafe fn f333<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_4()
}

unsafe fn f334<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T4 {
    ((*a0).cc2_4_mut() as *mut T4)
}

unsafe fn f335<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T4 {
    ((*a0).cc2_4() as *const T4)
}

unsafe fn f336<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T5) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V5(a0)
}

unsafe fn f337<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T5) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V5(a0)
}

unsafe fn f338<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T5) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V5(a0)
}

unsafe fn f339<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T5) {
    *a0 = Variant8::V5(a1)
}

unsafe fn f340<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T5) {
    *a0 = Variant8::V5(a1)
}

unsafe fn f341<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T5) {
    *a0 = Variant8::V5(a1)
}

unsafe fn f342<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_5()
}

unsafe fn f343<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T5 {
    ((*a0).cc2_5_mut() as *mut T5)
}

unsafe fn f344<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T5 {
    ((*a0).cc2_5() as *const T5)
}

unsafe fn f345<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T6) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V6(a0)
}

unsafe fn f346<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T6) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V6(a0)
}

unsafe fn f347<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T6) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V6(a0)
}

unsafe fn f348<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T6) {
    *a0 = Variant8::V6(a1)
}

unsafe fn f349<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T6) {
    *a0 = Variant8::V6(a1)
}

unsafe fn f350<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T6) {
    *a0 = Variant8::V6(a1)
}

unsafe fn f351<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_6()
}

unsafe fn f352<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T6 {
    ((*a0).cc2_6_mut() as *mut T6)
}

unsafe fn f353<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T6 {
    ((*a0).cc2_6() as *const T6)
}

unsafe fn f354<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T7) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V7(a0)
}

unsafe fn f355<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T7) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V7(a0)
}

unsafe fn f356<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T7) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V7(a0)
}

unsafe fn f357<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T7) {
    *a0 = Variant8::V7(a1)
}

unsafe fn f358<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T7) {
    *a0 = Variant8::V7(a1)
}

unsafe fn f359<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T7) {
    *a0 = Variant8::V7(a1)
}

unsafe fn f360<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_7()
}

unsafe fn f361<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T7 {
    ((*a0).cc2_7_mut() as *mut T7)
}

unsafe fn f362<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T7 {
    ((*a0).cc2_7() as *const T7)
}

unsafe fn f363<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T8) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V8(a0)
}

unsafe fn f364<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T8) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V8(a0)
}

unsafe fn f365<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T8) -> Variant8<T1, T2, T3, T4, T5, T6, T7, T8> {
    Variant8::V8(a0)
}

unsafe fn f366<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T8) {
    *a0 = Variant8::V8(a1)
}

unsafe fn f367<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T8) {
    *a0 = Variant8::V8(a1)
}

unsafe fn f368<T1, T2, T3, T4, T5, T6, T7, T8>(a0: &mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>, a1: T8) {
    *a0 = Variant8::V8(a1)
}

unsafe fn f369<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> bool {
    a0.cc2_holds_8()
}

unsafe fn f370<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *mut Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *mut T8 {
    ((*a0).cc2_8_mut() as *mut T8)
}

unsafe fn f371<T1, T2, T3, T4, T5, T6, T7, T8>(a0: *const Variant8<T1, T2, T3, T4, T5, T6, T7, T8>) -> *const T8 {
    ((*a0).cc2_8() as *const T8)
}

