// Copyright (c) 2022-present INESC-ID.
// Distributed under the MIT license that can be found in the LICENSE file.

// std::variant<A, B, ..> -> VariantN<Value<A>, Value<B>, ..>: the payload lives
// behind an Rc so std::get<T> can hand out a Ptr<T>, exactly the way
// rules/optional maps std::optional<T> to Option<Value<T>>.  The enum is the
// same enum as the unsafe model uses; only the payload wrapper differs, which
// is the same split rules/tuple has between (T1, T2) and (Value<T1>, Value<T2>).
//
// COPYING IS DEEP, and that is the whole reason a refcount overlay exists here
// rather than just reusing the unsafe bodies.  A `.clone()` of
// VariantN<Value<T>, ..> clones the Rc HANDLE, so the copy would ALIAS the
// original -- which is precisely the aliasing bug rules/pair records under
// "ambiguous translation rule".  `cc2_deep_clone` clones the pointed-to VALUE.
// C++ `data_ = orig.data_` copies the object, so aliasing would be wrong, and
// progir.cpp:98 OperandAttr::operator= is exactly that line.
//
// GENERATED by iso/variant/gen.py -- edit that, not this.

use libcc2rs::*;
use std::cell::RefCell;
use std::rc::Rc;

// ---- arity 2 -----------------------------------------------------------

fn t1<T1: Default, T2: Default>() -> Variant2<Value<T1>, Value<T2>> {
    Default::default()
}

fn f1<T1: Default, T2: Default>() -> Variant2<Value<T1>, Value<T2>> {
    Default::default()
}

fn f2<T1: DeepClone, T2: DeepClone>(a0: Variant2<Value<T1>, Value<T2>>) -> Variant2<Value<T1>, Value<T2>> {
    a0.cc2_deep_clone()
}

fn f3<T1: Default, T2: Default>(a0: &mut Variant2<Value<T1>, Value<T2>>) -> Variant2<Value<T1>, Value<T2>> {
    std::mem::take(&mut *a0)
}

fn f4<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: Variant2<Value<T1>, Value<T2>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f5<T1: Default + ByteRepr, T2: Default + ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: &mut Variant2<Value<T1>, Value<T2>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f6<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> u64 {
    a0.cc2_index()
}

fn f7<T1: PartialEq, T2: PartialEq>(a0: Variant2<Value<T1>, Value<T2>>, a1: Variant2<Value<T1>, Value<T2>>) -> bool {
    (a0 == a1)
}

fn f8<T1: PartialEq, T2: PartialEq>(a0: Variant2<Value<T1>, Value<T2>>, a1: Variant2<Value<T1>, Value<T2>>) -> bool {
    (a0 != a1)
}

fn f9<T1, T2>(a0: T1) -> Variant2<Value<T1>, Value<T2>> {
    Variant2::V1(Rc::new(RefCell::new(a0)))
}

fn f10<T1, T2>(a0: T1) -> Variant2<Value<T1>, Value<T2>> {
    Variant2::V1(Rc::new(RefCell::new(a0)))
}

fn f11<T1, T2>(a0: T1) -> Variant2<Value<T1>, Value<T2>> {
    Variant2::V1(Rc::new(RefCell::new(a0)))
}

fn f12<T1: ByteRepr, T2: ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: T1) {
    a0.write(Variant2::V1(Rc::new(RefCell::new(a1))))
}

fn f13<T1: ByteRepr, T2: ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: T1) {
    a0.write(Variant2::V1(Rc::new(RefCell::new(a1))))
}

fn f14<T1: ByteRepr, T2: ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: T1) {
    a0.write(Variant2::V1(Rc::new(RefCell::new(a1))))
}

fn f15<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> bool {
    a0.cc2_holds_1()
}

fn f16<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f17<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f18<T1, T2>(a0: T2) -> Variant2<Value<T1>, Value<T2>> {
    Variant2::V2(Rc::new(RefCell::new(a0)))
}

fn f19<T1, T2>(a0: T2) -> Variant2<Value<T1>, Value<T2>> {
    Variant2::V2(Rc::new(RefCell::new(a0)))
}

fn f20<T1, T2>(a0: T2) -> Variant2<Value<T1>, Value<T2>> {
    Variant2::V2(Rc::new(RefCell::new(a0)))
}

fn f21<T1: ByteRepr, T2: ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: T2) {
    a0.write(Variant2::V2(Rc::new(RefCell::new(a1))))
}

fn f22<T1: ByteRepr, T2: ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: T2) {
    a0.write(Variant2::V2(Rc::new(RefCell::new(a1))))
}

fn f23<T1: ByteRepr, T2: ByteRepr>(a0: Ptr<Variant2<Value<T1>, Value<T2>>>, a1: T2) {
    a0.write(Variant2::V2(Rc::new(RefCell::new(a1))))
}

fn f24<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> bool {
    a0.cc2_holds_2()
}

fn f25<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f26<T1, T2>(a0: Variant2<Value<T1>, Value<T2>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

// ---- arity 3 -----------------------------------------------------------

fn t2<T1: Default, T2: Default, T3: Default>() -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Default::default()
}

fn f27<T1: Default, T2: Default, T3: Default>() -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Default::default()
}

fn f28<T1: DeepClone, T2: DeepClone, T3: DeepClone>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    a0.cc2_deep_clone()
}

fn f29<T1: Default, T2: Default, T3: Default>(a0: &mut Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    std::mem::take(&mut *a0)
}

fn f30<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr, T3: DeepClone + ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: Variant3<Value<T1>, Value<T2>, Value<T3>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f31<T1: Default + ByteRepr, T2: Default + ByteRepr, T3: Default + ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: &mut Variant3<Value<T1>, Value<T2>, Value<T3>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f32<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> u64 {
    a0.cc2_index()
}

fn f33<T1: PartialEq, T2: PartialEq, T3: PartialEq>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>, a1: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> bool {
    (a0 == a1)
}

fn f34<T1: PartialEq, T2: PartialEq, T3: PartialEq>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>, a1: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> bool {
    (a0 != a1)
}

fn f35<T1, T2, T3>(a0: T1) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V1(Rc::new(RefCell::new(a0)))
}

fn f36<T1, T2, T3>(a0: T1) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V1(Rc::new(RefCell::new(a0)))
}

fn f37<T1, T2, T3>(a0: T1) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V1(Rc::new(RefCell::new(a0)))
}

fn f38<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T1) {
    a0.write(Variant3::V1(Rc::new(RefCell::new(a1))))
}

fn f39<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T1) {
    a0.write(Variant3::V1(Rc::new(RefCell::new(a1))))
}

fn f40<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T1) {
    a0.write(Variant3::V1(Rc::new(RefCell::new(a1))))
}

fn f41<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> bool {
    a0.cc2_holds_1()
}

fn f42<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f43<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f44<T1, T2, T3>(a0: T2) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V2(Rc::new(RefCell::new(a0)))
}

fn f45<T1, T2, T3>(a0: T2) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V2(Rc::new(RefCell::new(a0)))
}

fn f46<T1, T2, T3>(a0: T2) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V2(Rc::new(RefCell::new(a0)))
}

fn f47<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T2) {
    a0.write(Variant3::V2(Rc::new(RefCell::new(a1))))
}

fn f48<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T2) {
    a0.write(Variant3::V2(Rc::new(RefCell::new(a1))))
}

fn f49<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T2) {
    a0.write(Variant3::V2(Rc::new(RefCell::new(a1))))
}

fn f50<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> bool {
    a0.cc2_holds_2()
}

fn f51<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f52<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f53<T1, T2, T3>(a0: T3) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V3(Rc::new(RefCell::new(a0)))
}

fn f54<T1, T2, T3>(a0: T3) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V3(Rc::new(RefCell::new(a0)))
}

fn f55<T1, T2, T3>(a0: T3) -> Variant3<Value<T1>, Value<T2>, Value<T3>> {
    Variant3::V3(Rc::new(RefCell::new(a0)))
}

fn f56<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T3) {
    a0.write(Variant3::V3(Rc::new(RefCell::new(a1))))
}

fn f57<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T3) {
    a0.write(Variant3::V3(Rc::new(RefCell::new(a1))))
}

fn f58<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr>(a0: Ptr<Variant3<Value<T1>, Value<T2>, Value<T3>>>, a1: T3) {
    a0.write(Variant3::V3(Rc::new(RefCell::new(a1))))
}

fn f59<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> bool {
    a0.cc2_holds_3()
}

fn f60<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f61<T1, T2, T3>(a0: Variant3<Value<T1>, Value<T2>, Value<T3>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

// ---- arity 4 -----------------------------------------------------------

fn t3<T1: Default, T2: Default, T3: Default, T4: Default>() -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Default::default()
}

fn f62<T1: Default, T2: Default, T3: Default, T4: Default>() -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Default::default()
}

fn f63<T1: DeepClone, T2: DeepClone, T3: DeepClone, T4: DeepClone>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    a0.cc2_deep_clone()
}

fn f64<T1: Default, T2: Default, T3: Default, T4: Default>(a0: &mut Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    std::mem::take(&mut *a0)
}

fn f65<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr, T3: DeepClone + ByteRepr, T4: DeepClone + ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f66<T1: Default + ByteRepr, T2: Default + ByteRepr, T3: Default + ByteRepr, T4: Default + ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: &mut Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f67<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> u64 {
    a0.cc2_index()
}

fn f68<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>, a1: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> bool {
    (a0 == a1)
}

fn f69<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>, a1: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> bool {
    (a0 != a1)
}

fn f70<T1, T2, T3, T4>(a0: T1) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V1(Rc::new(RefCell::new(a0)))
}

fn f71<T1, T2, T3, T4>(a0: T1) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V1(Rc::new(RefCell::new(a0)))
}

fn f72<T1, T2, T3, T4>(a0: T1) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V1(Rc::new(RefCell::new(a0)))
}

fn f73<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T1) {
    a0.write(Variant4::V1(Rc::new(RefCell::new(a1))))
}

fn f74<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T1) {
    a0.write(Variant4::V1(Rc::new(RefCell::new(a1))))
}

fn f75<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T1) {
    a0.write(Variant4::V1(Rc::new(RefCell::new(a1))))
}

fn f76<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> bool {
    a0.cc2_holds_1()
}

fn f77<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f78<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f79<T1, T2, T3, T4>(a0: T2) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V2(Rc::new(RefCell::new(a0)))
}

fn f80<T1, T2, T3, T4>(a0: T2) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V2(Rc::new(RefCell::new(a0)))
}

fn f81<T1, T2, T3, T4>(a0: T2) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V2(Rc::new(RefCell::new(a0)))
}

fn f82<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T2) {
    a0.write(Variant4::V2(Rc::new(RefCell::new(a1))))
}

fn f83<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T2) {
    a0.write(Variant4::V2(Rc::new(RefCell::new(a1))))
}

fn f84<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T2) {
    a0.write(Variant4::V2(Rc::new(RefCell::new(a1))))
}

fn f85<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> bool {
    a0.cc2_holds_2()
}

fn f86<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f87<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f88<T1, T2, T3, T4>(a0: T3) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V3(Rc::new(RefCell::new(a0)))
}

fn f89<T1, T2, T3, T4>(a0: T3) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V3(Rc::new(RefCell::new(a0)))
}

fn f90<T1, T2, T3, T4>(a0: T3) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V3(Rc::new(RefCell::new(a0)))
}

fn f91<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T3) {
    a0.write(Variant4::V3(Rc::new(RefCell::new(a1))))
}

fn f92<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T3) {
    a0.write(Variant4::V3(Rc::new(RefCell::new(a1))))
}

fn f93<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T3) {
    a0.write(Variant4::V3(Rc::new(RefCell::new(a1))))
}

fn f94<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> bool {
    a0.cc2_holds_3()
}

fn f95<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f96<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f97<T1, T2, T3, T4>(a0: T4) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V4(Rc::new(RefCell::new(a0)))
}

fn f98<T1, T2, T3, T4>(a0: T4) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V4(Rc::new(RefCell::new(a0)))
}

fn f99<T1, T2, T3, T4>(a0: T4) -> Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>> {
    Variant4::V4(Rc::new(RefCell::new(a0)))
}

fn f100<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T4) {
    a0.write(Variant4::V4(Rc::new(RefCell::new(a1))))
}

fn f101<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T4) {
    a0.write(Variant4::V4(Rc::new(RefCell::new(a1))))
}

fn f102<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr>(a0: Ptr<Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>>, a1: T4) {
    a0.write(Variant4::V4(Rc::new(RefCell::new(a1))))
}

fn f103<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> bool {
    a0.cc2_holds_4()
}

fn f104<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f105<T1, T2, T3, T4>(a0: Variant4<Value<T1>, Value<T2>, Value<T3>, Value<T4>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

// ---- arity 5 -----------------------------------------------------------

fn t4<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>() -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Default::default()
}

fn f106<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>() -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Default::default()
}

fn f107<T1: DeepClone, T2: DeepClone, T3: DeepClone, T4: DeepClone, T5: DeepClone>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    a0.cc2_deep_clone()
}

fn f108<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default>(a0: &mut Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    std::mem::take(&mut *a0)
}

fn f109<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr, T3: DeepClone + ByteRepr, T4: DeepClone + ByteRepr, T5: DeepClone + ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f110<T1: Default + ByteRepr, T2: Default + ByteRepr, T3: Default + ByteRepr, T4: Default + ByteRepr, T5: Default + ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: &mut Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f111<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> u64 {
    a0.cc2_index()
}

fn f112<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>, a1: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    (a0 == a1)
}

fn f113<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>, a1: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    (a0 != a1)
}

fn f114<T1, T2, T3, T4, T5>(a0: T1) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V1(Rc::new(RefCell::new(a0)))
}

fn f115<T1, T2, T3, T4, T5>(a0: T1) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V1(Rc::new(RefCell::new(a0)))
}

fn f116<T1, T2, T3, T4, T5>(a0: T1) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V1(Rc::new(RefCell::new(a0)))
}

fn f117<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T1) {
    a0.write(Variant5::V1(Rc::new(RefCell::new(a1))))
}

fn f118<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T1) {
    a0.write(Variant5::V1(Rc::new(RefCell::new(a1))))
}

fn f119<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T1) {
    a0.write(Variant5::V1(Rc::new(RefCell::new(a1))))
}

fn f120<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    a0.cc2_holds_1()
}

fn f121<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f122<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f123<T1, T2, T3, T4, T5>(a0: T2) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V2(Rc::new(RefCell::new(a0)))
}

fn f124<T1, T2, T3, T4, T5>(a0: T2) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V2(Rc::new(RefCell::new(a0)))
}

fn f125<T1, T2, T3, T4, T5>(a0: T2) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V2(Rc::new(RefCell::new(a0)))
}

fn f126<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T2) {
    a0.write(Variant5::V2(Rc::new(RefCell::new(a1))))
}

fn f127<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T2) {
    a0.write(Variant5::V2(Rc::new(RefCell::new(a1))))
}

fn f128<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T2) {
    a0.write(Variant5::V2(Rc::new(RefCell::new(a1))))
}

fn f129<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    a0.cc2_holds_2()
}

fn f130<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f131<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f132<T1, T2, T3, T4, T5>(a0: T3) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V3(Rc::new(RefCell::new(a0)))
}

fn f133<T1, T2, T3, T4, T5>(a0: T3) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V3(Rc::new(RefCell::new(a0)))
}

fn f134<T1, T2, T3, T4, T5>(a0: T3) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V3(Rc::new(RefCell::new(a0)))
}

fn f135<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T3) {
    a0.write(Variant5::V3(Rc::new(RefCell::new(a1))))
}

fn f136<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T3) {
    a0.write(Variant5::V3(Rc::new(RefCell::new(a1))))
}

fn f137<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T3) {
    a0.write(Variant5::V3(Rc::new(RefCell::new(a1))))
}

fn f138<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    a0.cc2_holds_3()
}

fn f139<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f140<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f141<T1, T2, T3, T4, T5>(a0: T4) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V4(Rc::new(RefCell::new(a0)))
}

fn f142<T1, T2, T3, T4, T5>(a0: T4) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V4(Rc::new(RefCell::new(a0)))
}

fn f143<T1, T2, T3, T4, T5>(a0: T4) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V4(Rc::new(RefCell::new(a0)))
}

fn f144<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T4) {
    a0.write(Variant5::V4(Rc::new(RefCell::new(a1))))
}

fn f145<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T4) {
    a0.write(Variant5::V4(Rc::new(RefCell::new(a1))))
}

fn f146<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T4) {
    a0.write(Variant5::V4(Rc::new(RefCell::new(a1))))
}

fn f147<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    a0.cc2_holds_4()
}

fn f148<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f149<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f150<T1, T2, T3, T4, T5>(a0: T5) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V5(Rc::new(RefCell::new(a0)))
}

fn f151<T1, T2, T3, T4, T5>(a0: T5) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V5(Rc::new(RefCell::new(a0)))
}

fn f152<T1, T2, T3, T4, T5>(a0: T5) -> Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>> {
    Variant5::V5(Rc::new(RefCell::new(a0)))
}

fn f153<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T5) {
    a0.write(Variant5::V5(Rc::new(RefCell::new(a1))))
}

fn f154<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T5) {
    a0.write(Variant5::V5(Rc::new(RefCell::new(a1))))
}

fn f155<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr>(a0: Ptr<Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>>, a1: T5) {
    a0.write(Variant5::V5(Rc::new(RefCell::new(a1))))
}

fn f156<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> bool {
    a0.cc2_holds_5()
}

fn f157<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f158<T1, T2, T3, T4, T5>(a0: Variant5<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

// ---- arity 6 -----------------------------------------------------------

fn t5<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>() -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Default::default()
}

fn f159<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>() -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Default::default()
}

fn f160<T1: DeepClone, T2: DeepClone, T3: DeepClone, T4: DeepClone, T5: DeepClone, T6: DeepClone>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    a0.cc2_deep_clone()
}

fn f161<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default>(a0: &mut Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    std::mem::take(&mut *a0)
}

fn f162<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr, T3: DeepClone + ByteRepr, T4: DeepClone + ByteRepr, T5: DeepClone + ByteRepr, T6: DeepClone + ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f163<T1: Default + ByteRepr, T2: Default + ByteRepr, T3: Default + ByteRepr, T4: Default + ByteRepr, T5: Default + ByteRepr, T6: Default + ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: &mut Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f164<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> u64 {
    a0.cc2_index()
}

fn f165<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>, a1: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    (a0 == a1)
}

fn f166<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>, a1: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    (a0 != a1)
}

fn f167<T1, T2, T3, T4, T5, T6>(a0: T1) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V1(Rc::new(RefCell::new(a0)))
}

fn f168<T1, T2, T3, T4, T5, T6>(a0: T1) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V1(Rc::new(RefCell::new(a0)))
}

fn f169<T1, T2, T3, T4, T5, T6>(a0: T1) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V1(Rc::new(RefCell::new(a0)))
}

fn f170<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T1) {
    a0.write(Variant6::V1(Rc::new(RefCell::new(a1))))
}

fn f171<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T1) {
    a0.write(Variant6::V1(Rc::new(RefCell::new(a1))))
}

fn f172<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T1) {
    a0.write(Variant6::V1(Rc::new(RefCell::new(a1))))
}

fn f173<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    a0.cc2_holds_1()
}

fn f174<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f175<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f176<T1, T2, T3, T4, T5, T6>(a0: T2) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V2(Rc::new(RefCell::new(a0)))
}

fn f177<T1, T2, T3, T4, T5, T6>(a0: T2) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V2(Rc::new(RefCell::new(a0)))
}

fn f178<T1, T2, T3, T4, T5, T6>(a0: T2) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V2(Rc::new(RefCell::new(a0)))
}

fn f179<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T2) {
    a0.write(Variant6::V2(Rc::new(RefCell::new(a1))))
}

fn f180<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T2) {
    a0.write(Variant6::V2(Rc::new(RefCell::new(a1))))
}

fn f181<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T2) {
    a0.write(Variant6::V2(Rc::new(RefCell::new(a1))))
}

fn f182<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    a0.cc2_holds_2()
}

fn f183<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f184<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f185<T1, T2, T3, T4, T5, T6>(a0: T3) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V3(Rc::new(RefCell::new(a0)))
}

fn f186<T1, T2, T3, T4, T5, T6>(a0: T3) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V3(Rc::new(RefCell::new(a0)))
}

fn f187<T1, T2, T3, T4, T5, T6>(a0: T3) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V3(Rc::new(RefCell::new(a0)))
}

fn f188<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T3) {
    a0.write(Variant6::V3(Rc::new(RefCell::new(a1))))
}

fn f189<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T3) {
    a0.write(Variant6::V3(Rc::new(RefCell::new(a1))))
}

fn f190<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T3) {
    a0.write(Variant6::V3(Rc::new(RefCell::new(a1))))
}

fn f191<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    a0.cc2_holds_3()
}

fn f192<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f193<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f194<T1, T2, T3, T4, T5, T6>(a0: T4) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V4(Rc::new(RefCell::new(a0)))
}

fn f195<T1, T2, T3, T4, T5, T6>(a0: T4) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V4(Rc::new(RefCell::new(a0)))
}

fn f196<T1, T2, T3, T4, T5, T6>(a0: T4) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V4(Rc::new(RefCell::new(a0)))
}

fn f197<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T4) {
    a0.write(Variant6::V4(Rc::new(RefCell::new(a1))))
}

fn f198<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T4) {
    a0.write(Variant6::V4(Rc::new(RefCell::new(a1))))
}

fn f199<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T4) {
    a0.write(Variant6::V4(Rc::new(RefCell::new(a1))))
}

fn f200<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    a0.cc2_holds_4()
}

fn f201<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f202<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f203<T1, T2, T3, T4, T5, T6>(a0: T5) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V5(Rc::new(RefCell::new(a0)))
}

fn f204<T1, T2, T3, T4, T5, T6>(a0: T5) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V5(Rc::new(RefCell::new(a0)))
}

fn f205<T1, T2, T3, T4, T5, T6>(a0: T5) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V5(Rc::new(RefCell::new(a0)))
}

fn f206<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T5) {
    a0.write(Variant6::V5(Rc::new(RefCell::new(a1))))
}

fn f207<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T5) {
    a0.write(Variant6::V5(Rc::new(RefCell::new(a1))))
}

fn f208<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T5) {
    a0.write(Variant6::V5(Rc::new(RefCell::new(a1))))
}

fn f209<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    a0.cc2_holds_5()
}

fn f210<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f211<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f212<T1, T2, T3, T4, T5, T6>(a0: T6) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V6(Rc::new(RefCell::new(a0)))
}

fn f213<T1, T2, T3, T4, T5, T6>(a0: T6) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V6(Rc::new(RefCell::new(a0)))
}

fn f214<T1, T2, T3, T4, T5, T6>(a0: T6) -> Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>> {
    Variant6::V6(Rc::new(RefCell::new(a0)))
}

fn f215<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T6) {
    a0.write(Variant6::V6(Rc::new(RefCell::new(a1))))
}

fn f216<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T6) {
    a0.write(Variant6::V6(Rc::new(RefCell::new(a1))))
}

fn f217<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr>(a0: Ptr<Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>>, a1: T6) {
    a0.write(Variant6::V6(Rc::new(RefCell::new(a1))))
}

fn f218<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> bool {
    a0.cc2_holds_6()
}

fn f219<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T6> {
    a0.cc2_ptr_6()
}

fn f220<T1, T2, T3, T4, T5, T6>(a0: Variant6<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>>) -> Ptr<T6> {
    a0.cc2_ptr_6()
}

// ---- arity 7 -----------------------------------------------------------

fn t6<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>() -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Default::default()
}

fn f221<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>() -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Default::default()
}

fn f222<T1: DeepClone, T2: DeepClone, T3: DeepClone, T4: DeepClone, T5: DeepClone, T6: DeepClone, T7: DeepClone>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    a0.cc2_deep_clone()
}

fn f223<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default>(a0: &mut Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    std::mem::take(&mut *a0)
}

fn f224<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr, T3: DeepClone + ByteRepr, T4: DeepClone + ByteRepr, T5: DeepClone + ByteRepr, T6: DeepClone + ByteRepr, T7: DeepClone + ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f225<T1: Default + ByteRepr, T2: Default + ByteRepr, T3: Default + ByteRepr, T4: Default + ByteRepr, T5: Default + ByteRepr, T6: Default + ByteRepr, T7: Default + ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: &mut Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f226<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> u64 {
    a0.cc2_index()
}

fn f227<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>, a1: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    (a0 == a1)
}

fn f228<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>, a1: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    (a0 != a1)
}

fn f229<T1, T2, T3, T4, T5, T6, T7>(a0: T1) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V1(Rc::new(RefCell::new(a0)))
}

fn f230<T1, T2, T3, T4, T5, T6, T7>(a0: T1) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V1(Rc::new(RefCell::new(a0)))
}

fn f231<T1, T2, T3, T4, T5, T6, T7>(a0: T1) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V1(Rc::new(RefCell::new(a0)))
}

fn f232<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T1) {
    a0.write(Variant7::V1(Rc::new(RefCell::new(a1))))
}

fn f233<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T1) {
    a0.write(Variant7::V1(Rc::new(RefCell::new(a1))))
}

fn f234<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T1) {
    a0.write(Variant7::V1(Rc::new(RefCell::new(a1))))
}

fn f235<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_1()
}

fn f236<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f237<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f238<T1, T2, T3, T4, T5, T6, T7>(a0: T2) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V2(Rc::new(RefCell::new(a0)))
}

fn f239<T1, T2, T3, T4, T5, T6, T7>(a0: T2) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V2(Rc::new(RefCell::new(a0)))
}

fn f240<T1, T2, T3, T4, T5, T6, T7>(a0: T2) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V2(Rc::new(RefCell::new(a0)))
}

fn f241<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T2) {
    a0.write(Variant7::V2(Rc::new(RefCell::new(a1))))
}

fn f242<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T2) {
    a0.write(Variant7::V2(Rc::new(RefCell::new(a1))))
}

fn f243<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T2) {
    a0.write(Variant7::V2(Rc::new(RefCell::new(a1))))
}

fn f244<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_2()
}

fn f245<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f246<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f247<T1, T2, T3, T4, T5, T6, T7>(a0: T3) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V3(Rc::new(RefCell::new(a0)))
}

fn f248<T1, T2, T3, T4, T5, T6, T7>(a0: T3) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V3(Rc::new(RefCell::new(a0)))
}

fn f249<T1, T2, T3, T4, T5, T6, T7>(a0: T3) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V3(Rc::new(RefCell::new(a0)))
}

fn f250<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T3) {
    a0.write(Variant7::V3(Rc::new(RefCell::new(a1))))
}

fn f251<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T3) {
    a0.write(Variant7::V3(Rc::new(RefCell::new(a1))))
}

fn f252<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T3) {
    a0.write(Variant7::V3(Rc::new(RefCell::new(a1))))
}

fn f253<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_3()
}

fn f254<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f255<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f256<T1, T2, T3, T4, T5, T6, T7>(a0: T4) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V4(Rc::new(RefCell::new(a0)))
}

fn f257<T1, T2, T3, T4, T5, T6, T7>(a0: T4) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V4(Rc::new(RefCell::new(a0)))
}

fn f258<T1, T2, T3, T4, T5, T6, T7>(a0: T4) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V4(Rc::new(RefCell::new(a0)))
}

fn f259<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T4) {
    a0.write(Variant7::V4(Rc::new(RefCell::new(a1))))
}

fn f260<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T4) {
    a0.write(Variant7::V4(Rc::new(RefCell::new(a1))))
}

fn f261<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T4) {
    a0.write(Variant7::V4(Rc::new(RefCell::new(a1))))
}

fn f262<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_4()
}

fn f263<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f264<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f265<T1, T2, T3, T4, T5, T6, T7>(a0: T5) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V5(Rc::new(RefCell::new(a0)))
}

fn f266<T1, T2, T3, T4, T5, T6, T7>(a0: T5) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V5(Rc::new(RefCell::new(a0)))
}

fn f267<T1, T2, T3, T4, T5, T6, T7>(a0: T5) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V5(Rc::new(RefCell::new(a0)))
}

fn f268<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T5) {
    a0.write(Variant7::V5(Rc::new(RefCell::new(a1))))
}

fn f269<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T5) {
    a0.write(Variant7::V5(Rc::new(RefCell::new(a1))))
}

fn f270<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T5) {
    a0.write(Variant7::V5(Rc::new(RefCell::new(a1))))
}

fn f271<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_5()
}

fn f272<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f273<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f274<T1, T2, T3, T4, T5, T6, T7>(a0: T6) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V6(Rc::new(RefCell::new(a0)))
}

fn f275<T1, T2, T3, T4, T5, T6, T7>(a0: T6) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V6(Rc::new(RefCell::new(a0)))
}

fn f276<T1, T2, T3, T4, T5, T6, T7>(a0: T6) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V6(Rc::new(RefCell::new(a0)))
}

fn f277<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T6) {
    a0.write(Variant7::V6(Rc::new(RefCell::new(a1))))
}

fn f278<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T6) {
    a0.write(Variant7::V6(Rc::new(RefCell::new(a1))))
}

fn f279<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T6) {
    a0.write(Variant7::V6(Rc::new(RefCell::new(a1))))
}

fn f280<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_6()
}

fn f281<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T6> {
    a0.cc2_ptr_6()
}

fn f282<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T6> {
    a0.cc2_ptr_6()
}

fn f283<T1, T2, T3, T4, T5, T6, T7>(a0: T7) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V7(Rc::new(RefCell::new(a0)))
}

fn f284<T1, T2, T3, T4, T5, T6, T7>(a0: T7) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V7(Rc::new(RefCell::new(a0)))
}

fn f285<T1, T2, T3, T4, T5, T6, T7>(a0: T7) -> Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>> {
    Variant7::V7(Rc::new(RefCell::new(a0)))
}

fn f286<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T7) {
    a0.write(Variant7::V7(Rc::new(RefCell::new(a1))))
}

fn f287<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T7) {
    a0.write(Variant7::V7(Rc::new(RefCell::new(a1))))
}

fn f288<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr>(a0: Ptr<Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>>, a1: T7) {
    a0.write(Variant7::V7(Rc::new(RefCell::new(a1))))
}

fn f289<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> bool {
    a0.cc2_holds_7()
}

fn f290<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T7> {
    a0.cc2_ptr_7()
}

fn f291<T1, T2, T3, T4, T5, T6, T7>(a0: Variant7<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>>) -> Ptr<T7> {
    a0.cc2_ptr_7()
}

// ---- arity 8 -----------------------------------------------------------

fn t7<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>() -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Default::default()
}

fn f292<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>() -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Default::default()
}

fn f293<T1: DeepClone, T2: DeepClone, T3: DeepClone, T4: DeepClone, T5: DeepClone, T6: DeepClone, T7: DeepClone, T8: DeepClone>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    a0.cc2_deep_clone()
}

fn f294<T1: Default, T2: Default, T3: Default, T4: Default, T5: Default, T6: Default, T7: Default, T8: Default>(a0: &mut Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    std::mem::take(&mut *a0)
}

fn f295<T1: DeepClone + ByteRepr, T2: DeepClone + ByteRepr, T3: DeepClone + ByteRepr, T4: DeepClone + ByteRepr, T5: DeepClone + ByteRepr, T6: DeepClone + ByteRepr, T7: DeepClone + ByteRepr, T8: DeepClone + ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) {
    a0.write(a1.cc2_deep_clone())
}

fn f296<T1: Default + ByteRepr, T2: Default + ByteRepr, T3: Default + ByteRepr, T4: Default + ByteRepr, T5: Default + ByteRepr, T6: Default + ByteRepr, T7: Default + ByteRepr, T8: Default + ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: &mut Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) {
    a0.write(std::mem::take(&mut *a1))
}

fn f297<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> u64 {
    a0.cc2_index()
}

fn f298<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq, T8: PartialEq>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>, a1: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    (a0 == a1)
}

fn f299<T1: PartialEq, T2: PartialEq, T3: PartialEq, T4: PartialEq, T5: PartialEq, T6: PartialEq, T7: PartialEq, T8: PartialEq>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>, a1: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    (a0 != a1)
}

fn f300<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T1) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V1(Rc::new(RefCell::new(a0)))
}

fn f301<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T1) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V1(Rc::new(RefCell::new(a0)))
}

fn f302<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T1) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V1(Rc::new(RefCell::new(a0)))
}

fn f303<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T1) {
    a0.write(Variant8::V1(Rc::new(RefCell::new(a1))))
}

fn f304<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T1) {
    a0.write(Variant8::V1(Rc::new(RefCell::new(a1))))
}

fn f305<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T1) {
    a0.write(Variant8::V1(Rc::new(RefCell::new(a1))))
}

fn f306<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_1()
}

fn f307<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f308<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T1> {
    a0.cc2_ptr_1()
}

fn f309<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T2) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V2(Rc::new(RefCell::new(a0)))
}

fn f310<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T2) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V2(Rc::new(RefCell::new(a0)))
}

fn f311<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T2) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V2(Rc::new(RefCell::new(a0)))
}

fn f312<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T2) {
    a0.write(Variant8::V2(Rc::new(RefCell::new(a1))))
}

fn f313<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T2) {
    a0.write(Variant8::V2(Rc::new(RefCell::new(a1))))
}

fn f314<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T2) {
    a0.write(Variant8::V2(Rc::new(RefCell::new(a1))))
}

fn f315<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_2()
}

fn f316<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f317<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T2> {
    a0.cc2_ptr_2()
}

fn f318<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T3) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V3(Rc::new(RefCell::new(a0)))
}

fn f319<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T3) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V3(Rc::new(RefCell::new(a0)))
}

fn f320<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T3) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V3(Rc::new(RefCell::new(a0)))
}

fn f321<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T3) {
    a0.write(Variant8::V3(Rc::new(RefCell::new(a1))))
}

fn f322<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T3) {
    a0.write(Variant8::V3(Rc::new(RefCell::new(a1))))
}

fn f323<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T3) {
    a0.write(Variant8::V3(Rc::new(RefCell::new(a1))))
}

fn f324<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_3()
}

fn f325<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f326<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T3> {
    a0.cc2_ptr_3()
}

fn f327<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T4) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V4(Rc::new(RefCell::new(a0)))
}

fn f328<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T4) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V4(Rc::new(RefCell::new(a0)))
}

fn f329<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T4) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V4(Rc::new(RefCell::new(a0)))
}

fn f330<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T4) {
    a0.write(Variant8::V4(Rc::new(RefCell::new(a1))))
}

fn f331<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T4) {
    a0.write(Variant8::V4(Rc::new(RefCell::new(a1))))
}

fn f332<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T4) {
    a0.write(Variant8::V4(Rc::new(RefCell::new(a1))))
}

fn f333<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_4()
}

fn f334<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f335<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T4> {
    a0.cc2_ptr_4()
}

fn f336<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T5) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V5(Rc::new(RefCell::new(a0)))
}

fn f337<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T5) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V5(Rc::new(RefCell::new(a0)))
}

fn f338<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T5) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V5(Rc::new(RefCell::new(a0)))
}

fn f339<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T5) {
    a0.write(Variant8::V5(Rc::new(RefCell::new(a1))))
}

fn f340<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T5) {
    a0.write(Variant8::V5(Rc::new(RefCell::new(a1))))
}

fn f341<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T5) {
    a0.write(Variant8::V5(Rc::new(RefCell::new(a1))))
}

fn f342<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_5()
}

fn f343<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f344<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T5> {
    a0.cc2_ptr_5()
}

fn f345<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T6) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V6(Rc::new(RefCell::new(a0)))
}

fn f346<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T6) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V6(Rc::new(RefCell::new(a0)))
}

fn f347<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T6) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V6(Rc::new(RefCell::new(a0)))
}

fn f348<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T6) {
    a0.write(Variant8::V6(Rc::new(RefCell::new(a1))))
}

fn f349<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T6) {
    a0.write(Variant8::V6(Rc::new(RefCell::new(a1))))
}

fn f350<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T6) {
    a0.write(Variant8::V6(Rc::new(RefCell::new(a1))))
}

fn f351<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_6()
}

fn f352<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T6> {
    a0.cc2_ptr_6()
}

fn f353<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T6> {
    a0.cc2_ptr_6()
}

fn f354<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T7) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V7(Rc::new(RefCell::new(a0)))
}

fn f355<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T7) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V7(Rc::new(RefCell::new(a0)))
}

fn f356<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T7) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V7(Rc::new(RefCell::new(a0)))
}

fn f357<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T7) {
    a0.write(Variant8::V7(Rc::new(RefCell::new(a1))))
}

fn f358<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T7) {
    a0.write(Variant8::V7(Rc::new(RefCell::new(a1))))
}

fn f359<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T7) {
    a0.write(Variant8::V7(Rc::new(RefCell::new(a1))))
}

fn f360<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_7()
}

fn f361<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T7> {
    a0.cc2_ptr_7()
}

fn f362<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T7> {
    a0.cc2_ptr_7()
}

fn f363<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T8) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V8(Rc::new(RefCell::new(a0)))
}

fn f364<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T8) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V8(Rc::new(RefCell::new(a0)))
}

fn f365<T1, T2, T3, T4, T5, T6, T7, T8>(a0: T8) -> Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>> {
    Variant8::V8(Rc::new(RefCell::new(a0)))
}

fn f366<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T8) {
    a0.write(Variant8::V8(Rc::new(RefCell::new(a1))))
}

fn f367<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T8) {
    a0.write(Variant8::V8(Rc::new(RefCell::new(a1))))
}

fn f368<T1: ByteRepr, T2: ByteRepr, T3: ByteRepr, T4: ByteRepr, T5: ByteRepr, T6: ByteRepr, T7: ByteRepr, T8: ByteRepr>(a0: Ptr<Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>>, a1: T8) {
    a0.write(Variant8::V8(Rc::new(RefCell::new(a1))))
}

fn f369<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> bool {
    a0.cc2_holds_8()
}

fn f370<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T8> {
    a0.cc2_ptr_8()
}

fn f371<T1, T2, T3, T4, T5, T6, T7, T8>(a0: Variant8<Value<T1>, Value<T2>, Value<T3>, Value<T4>, Value<T5>, Value<T6>, Value<T7>, Value<T8>>) -> Ptr<T8> {
    a0.cc2_ptr_8()
}

